"""init db

Revision ID: 001
Revises:
Create Date: 2024-01-01 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_groups',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('collect_interval', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('data_sources',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('group_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('HOTLIST', 'ACCOUNT', 'VIDEO', 'CUSTOM', name='datasourcetype'), nullable=False),
    sa.Column('collector_type', sa.Enum('CONFIGURABLE', 'PLUGIN', name='collectortype'), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'ERROR', name='sourcestatus'), nullable=False),
    sa.Column('last_collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['source_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_data_sources_group_id', 'data_sources', ['group_id'], unique=False)
    op.create_index('ix_data_sources_is_active', 'data_sources', ['is_active'], unique=False)
    op.create_index('ix_data_sources_status', 'data_sources', ['status'], unique=False)
    op.create_index('ix_data_sources_type', 'data_sources', ['type'], unique=False)

    op.create_table('clues',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('source_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('cover_image', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('heat_value', sa.String(length=100), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unique_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clues_collected_at', 'clues', ['collected_at'], unique=False)
    op.create_index('ix_clues_source_collected', 'clues', ['source_id', 'collected_at'], unique=False)
    op.create_index('ix_clues_source_id', 'clues', ['source_id'], unique=False)
    op.create_index('ix_clues_unique_hash', 'clues', ['unique_hash'], unique=False)

    op.create_table('collect_logs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('source_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', 'PARTIAL', name='collectstatus'), nullable=False),
    sa.Column('items_count', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_collect_logs_source_id', 'collect_logs', ['source_id'], unique=False)
    op.create_index('ix_collect_logs_source_started', 'collect_logs', ['source_id', 'started_at'], unique=False)
    op.create_index('ix_collect_logs_started_at', 'collect_logs', ['started_at'], unique=False)
    op.create_index('ix_collect_logs_status', 'collect_logs', ['status'], unique=False)

    op.create_table('hotlist_history',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('clue_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('change_type', sa.Enum('NEW', 'RANK_UP', 'RANK_DOWN', 'OFF', name='changetype'), nullable=False),
    sa.Column('old_rank', sa.Integer(), nullable=True),
    sa.Column('new_rank', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clue_id'], ['clues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hotlist_history_clue_id', 'hotlist_history', ['clue_id'], unique=False)
    op.create_index('ix_hotlist_history_recorded_at', 'hotlist_history', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_hotlist_history_recorded_at', table_name='hotlist_history')
    op.drop_index('ix_hotlist_history_clue_id', table_name='hotlist_history')
    op.drop_table('hotlist_history')
    op.drop_index('ix_collect_logs_status', table_name='collect_logs')
    op.drop_index('ix_collect_logs_started_at', table_name='collect_logs')
    op.drop_index('ix_collect_logs_source_started', table_name='collect_logs')
    op.drop_index('ix_collect_logs_source_id', table_name='collect_logs')
    op.drop_table('collect_logs')
    op.drop_index('ix_clues_unique_hash', table_name='clues')
    op.drop_index('ix_clues_source_id', table_name='clues')
    op.drop_index('ix_clues_source_collected', table_name='clues')
    op.drop_index('ix_clues_collected_at', table_name='clues')
    op.drop_table('clues')
    op.drop_index('ix_data_sources_type', table_name='data_sources')
    op.drop_index('ix_data_sources_status', table_name='data_sources')
    op.drop_index('ix_data_sources_is_active', table_name='data_sources')
    op.drop_index('ix_data_sources_group_id', table_name='data_sources')
    op.drop_table('data_sources')
    op.drop_table('source_groups')
    # ### end Alembic commands ###
